### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by jswhisperer** [aaronhuggins/kodi-api#1]
Firstly, awesome work, it looks really fully fledged and polished.

Was wondering you wanted to add client.listMethods(); to the docs, I wasnt able to find any of the methods till i went through the src.

cheers

**Comment by aaronhuggins** [comment]
Thanks @gregpalaci. Glad you're liking it so far.

I've already got the method listed in the generated docs for the client.

https://aaronhuggins.github.io/kodi-api/classes/kodiclient.html#listmethods

Could you be more specific, or clarify what you're asking for?

**Comment by jswhisperer** [comment]
Oh I guess the link doesnt work (for me?) 

Documentation for the client is available in ./docs.

on the readme

**Comment by aaronhuggins** [comment]
@gregpalaci I can't seem to reproduce the broken link issue. I've tried two machines, linux and windows OS, and Brave, Firefox, and Chrome browsers. Links to the docs appear to work on the following pages:

- https://www.npmjs.com/package/kodi-api
- https://github.com/aaronhuggins/kodi-api
- https://aaronhuggins.github.io/kodi-api/

All the links for documentation or homepage point to https://aaronhuggins.github.io/kodi-api/ which appears to be accessible to me. I'll wait to close for 7 days pending steps to reproduce from you, because I definitely want the docs to be accessible.
